- name: filters or functions
  hosts: node1
  tasks: #list of tasks/collections/modules
  - name: default value
    ansible.builtin.debug:
      msg: "I am {{ Name | default('Avinash') }}"

  - name: lowercase
    vars:
      Name: "Avinash"
    ansible.builtin.debug:
      msg: "I am {{ Name | lower }}"
  
  - name: uppercase
    vars:
      Name: "DevOps"
    ansible.builtin.debug:
      msg: "I am {{ Name | upper }}"

  - name: removing duplicate
    vars:
      Numbers: [1,1,1,2,2,3,3,4,4]
    ansible.builtin.debug:
      msg: "{{ Numbers | unique }}"

  - name: max and min
    vars:
      ages: [13,25,30,45,60,80,100]
    ansible.builtin.debug:
      msg: "min age is: {{ ages | min}} , max age is: {{ ages | max }}" 

- name: dictonary to list
  hosts: node1
  vars:
   mydict:
      Course: "AWS"
      Trainer: "Avin"
      Mode: "Online"
  tasks: # list of tasks/modules/collections
  - name: Before converting  
    ansible.builtin.debug:
      msg: "Before converting {{ mydict }}"

  - name: After converting
    ansible.builtin.debug:
      msg: "After converting {{ mydict | dict2items }}"

