- name: filters or functions
  hosts: node1
  tasks: #list of tasks/collections/modules
  - name: default value
    ansible.builtin.debug:
      msg: "I am {{ Name | default('Avinash') }}"

  - name: lowercase
    vars:
      Name: "Avinash"
    ansible.builtin.debug:
      msg: "I am {{ Name | lower }}"
  
  - name: uppercase
    vars:
      Name: "DevOps"
    ansible.builtin.debug:
      msg: "I am {{ Name | upper }}"

  - name: removing duplicate
    vars:
      Numbers: [1,1,1,2,2,3,3,4,4]
    ansible.builtin.debug:
      msg: "{{ Numbers | unique }}"